import { MOVEMENT_METHOD, MOVE_DETAIL } from '../enums/PokemonMovement';

export const TableMethod /* : TableDataMethod */ = {
  [MOVEMENT_METHOD.LEVELUP]: [],
  [MOVEMENT_METHOD.EGG]: [],
  [MOVEMENT_METHOD.MACHINE]: [],
  [MOVEMENT_METHOD.TUTOR]: [],
};

export const HeaderMethod = {
  [MOVEMENT_METHOD.LEVELUP]: [
    MOVE_DETAIL.MOVE,
    MOVE_DETAIL.TYPE,
    MOVE_DETAIL.CLASS,
    MOVE_DETAIL.LEVEL,
  ],
  [MOVEMENT_METHOD.EGG]: [MOVE_DETAIL.MOVE, MOVE_DETAIL.TYPE, MOVE_DETAIL.CLASS],
  [MOVEMENT_METHOD.MACHINE]: [MOVE_DETAIL.MOVE, MOVE_DETAIL.TYPE, MOVE_DETAIL.CLASS],
  [MOVEMENT_METHOD.TUTOR]: [MOVE_DETAIL.MOVE, MOVE_DETAIL.TYPE, MOVE_DETAIL.CLASS],
};
