import { POKEMON_TYPE } from '../enums/PokemonType';
import { TypesDamages } from '../interfaces/TypesDamages';

/* export const TYPES_DAMAGES: TypesDamages = [
  {
    name: 'normal',
    color: {
      base: 'hsl(60,10.1%,69%)',
      lighten: 'hsl(60,10.1%,89%)',
      darken: 'hsl(60,10.1%,49%)',
    },
    type: 'normal',
    damage: {
      normal: 1,
      fire: 1,
      water: 1,
      electric: 1,
      grass: 1,
      ice: 1,
      fighting: 1,
      poison: 1,
      ground: 1,
      flying: 1,
      psychic: 1,
      bug: 1,
      rock: 0.5,
      ghost: 0,
      dragon: 1,
      dark: 1,
      steel: 0.5,
      fairy: 1,
    },
    weakness: ['fighting'],
  },
  {
    name: 'fire',
    color: {
      base: 'hsl(25.6,84.8%,56.1%)',
      lighten: 'hsl(25.6,84.8%,76.1%)',
      darken: 'hsl(25.6,84.8%,36.1%)',
    },
    type: 'fire',
    damage: {
      normal: 1,
      fire: 0.5,
      water: 0.5,
      electric: 1,
      grass: 2,
      ice: 2,
      fighting: 1,
      poison: 1,
      ground: 1,
      flying: 1,
      psychic: 1,
      bug: 2,
      rock: 0.5,
      ghost: 1,
      dragon: 0.5,
      dark: 1,
      steel: 2,
      fairy: 1,
    },
    weakness: ['water', 'ground', 'rock'],
  },
  {
    name: 'water',
    color: {
      base: 'hsl(220.9,82.5%,66.5%)',
      lighten: 'hsl(220.9,82.5%,86.5%)',
      darken: 'hsl(220.9,82.5%,46.5%)',
    },
    type: 'water',
    damage: {
      normal: 1,
      fire: 2,
      water: 0.5,
      electric: 0.5,
      grass: 0.5,
      ice: 1,
      fighting: 1,
      poison: 1,
      ground: 2,
      flying: 1,
      psychic: 1,
      bug: 1,
      rock: 2,
      ghost: 1,
      dragon: 0.5,
      dark: 1,
      steel: 1,
      fairy: 1,
    },
    weakness: ['grass', 'electric'],
  },
  {
    name: 'electric',
    color: {
      base: 'hsl(48.5,92.7%,57.1%)',
      lighten: 'hsl(48.5,92.7%,77.1%)',
      darken: 'hsl(48.5,92.7%,37.1%)',
    },
    type: 'electric',
    damage: {
      normal: 1,
      fire: 1,
      water: 2,
      electric: 0.5,
      grass: 0.5,
      ice: 1,
      fighting: 1,
      poison: 1,
      ground: 0,
      flying: 2,
      psychic: 1,
      bug: 1,
      rock: 1,
      ghost: 1,
      dragon: 0.5,
      dark: 1,
      steel: 1,
      fairy: 1,
    },
    weakness: ['ground'],
  },
  {
    name: 'grass',
    color: {
      base: 'hsl(97.6,52.3%,53.9%)',
      lighten: 'hsl(97.6,52.3%,73.9%)',
      darken: 'hsl(97.6,52.3%,33.9%)',
    },
    type: 'grass',
    damage: {
      normal: 1,
      fire: 0.5,
      water: 2,
      electric: 1,
      grass: 0.5,
      ice: 1,
      fighting: 1,
      poison: 0.5,
      ground: 2,
      flying: 0.5,
      psychic: 1,
      bug: 0.5,
      rock: 2,
      ghost: 1,
      dragon: 0.5,
      dark: 1,
      steel: 0.5,
      fairy: 1,
    },
    weakness: ['fire', 'ice', 'poison', 'flying', 'bug'],
  },
  {
    name: 'ice',
    color: {
      base: 'hsl(177.3,46.9%,72%)',
      lighten: 'hsl(177.3,46.9%,92%)',
      darken: 'hsl(177.3,46.9%,52%)',
    },
    type: 'ice',
    damage: {
      normal: 1,
      fire: 0.5,
      water: 0.5,
      electric: 1,
      grass: 2,
      ice: 0.5,
      fighting: 1,
      poison: 1,
      ground: 2,
      flying: 2,
      psychic: 1,
      bug: 1,
      rock: 1,
      ghost: 1,
      dragon: 2,
      dark: 1,
      steel: 0.5,
      fairy: 1,
    },
    weakness: ['fire', 'fighting', 'rock', 'steel'],
  },
  {
    name: 'fighting',
    color: {
      base: 'hsl(2.3,65.8%,45.9%)',
      lighten: 'hsl(2.3,65.8%,65.9%)',
      darken: 'hsl(2.3,65.8%,25.9%)',
    },
    type: 'fighting',
    damage: {
      normal: 2,
      fire: 1,
      water: 1,
      electric: 1,
      grass: 1,
      ice: 2,
      fighting: 1,
      poison: 0.5,
      ground: 1,
      flying: 0.5,
      psychic: 0.5,
      bug: 0.5,
      rock: 2,
      ghost: 0,
      dragon: 1,
      dark: 2,
      steel: 2,
      fairy: 0.5,
    },
    weakness: ['flying', 'psychic', 'fairy'],
  },
  {
    name: 'poison',
    color: {
      base: 'hsl(301.2,44.9%,44.1%)',
      lighten: 'hsl(301.2,44.9%,64.1%)',
      darken: 'hsl(301.2,44.9%,24.1%)',
    },
    type: 'poison',
    damage: {
      normal: 1,
      fire: 1,
      water: 1,
      electric: 1,
      grass: 2,
      ice: 1,
      fighting: 1,
      poison: 0.5,
      ground: 0.5,
      flying: 1,
      psychic: 1,
      bug: 1,
      rock: 0.5,
      ghost: 0.5,
      dragon: 1,
      dark: 1,
      steel: 0,
      fairy: 2,
    },
    weakness: ['ground', 'psychic'],
  },
  {
    name: 'ground',
    color: {
      base: 'hsl(43.2,68.3%,64.1%)',
      lighten: 'hsl(43.2,68.3%,84.1%)',
      darken: 'hsl(43.2,68.3%,44.1%)',
    },
    type: 'ground',
    damage: {
      normal: 1,
      fire: 2,
      water: 1,
      electric: 2,
      grass: 0.5,
      ice: 1,
      fighting: 1,
      poison: 2,
      ground: 1,
      flying: 0,
      psychic: 1,
      bug: 0.5,
      rock: 2,
      ghost: 1,
      dragon: 1,
      dark: 1,
      steel: 2,
      fairy: 1,
    },
    weakness: ['water', 'grass', 'ice'],
  },
  {
    name: 'flying',
    color: {
      base: 'hsl(255.6,80.6%,75.7%)',
      lighten: 'hsl(255.6,80.6%,95.7%)',
      darken: 'hsl(255.6,80.6%,55.7%)',
    },
    type: 'flying',
    damage: {
      normal: 1,
      fire: 1,
      water: 1,
      electric: 0.5,
      grass: 2,
      ice: 1,
      fighting: 2,
      poison: 1,
      ground: 1,
      flying: 1,
      psychic: 1,
      bug: 2,
      rock: 0.5,
      ghost: 1,
      dragon: 1,
      dark: 1,
      steel: 0.5,
      fairy: 1,
    },
    weakness: ['electric', 'ice', 'rock'],
  },
  {
    name: 'psychic',
    color: {
      base: 'hsl(341.7,93.2%,65.5%)',
      lighten: 'hsl(341.7,93.2%,85.5%)',
      darken: 'hsl(341.7,93.2%,45.5%)',
    },
    type: 'psychic',
    damage: {
      normal: 1,
      fire: 1,
      water: 1,
      electric: 1,
      grass: 1,
      ice: 1,
      fighting: 2,
      poison: 2,
      ground: 1,
      flying: 1,
      psychic: 0.5,
      bug: 1,
      rock: 1,
      ghost: 1,
      dragon: 1,
      dark: 0,
      steel: 0.5,
      fairy: 1,
    },
    weakness: ['bug', 'ghost', 'dark'],
  },
  {
    name: 'bug',
    color: {
      base: 'hsl(67.2,75.4%,41.4%)',
      lighten: 'hsl(67.2,75.4%,61.4%)',
      darken: 'hsl(67.2,75.4%,21.4%)',
    },
    type: 'bug',
    damage: {
      normal: 1,
      fire: 0.5,
      water: 1,
      electric: 1,
      grass: 2,
      ice: 1,
      fighting: 0.5,
      poison: 0.5,
      ground: 1,
      flying: 0.5,
      psychic: 2,
      bug: 1,
      rock: 1,
      ghost: 0.5,
      dragon: 1,
      dark: 2,
      steel: 0.5,
      fairy: 0.5,
    },
    weakness: ['fire', 'flying', 'rock'],
  },
  {
    name: 'rock',
    color: {
      base: 'hsl(50.2,54.2%,46.3%)',
      lighten: 'hsl(50.2,54.2%,66.3%)',
      darken: 'hsl(50.2,54.2%,26.3%)',
    },
    type: 'rock',
    damage: {
      normal: 1,
      fire: 2,
      water: 1,
      electric: 1,
      grass: 1,
      ice: 2,
      fighting: 0.5,
      poison: 1,
      ground: 0.5,
      flying: 2,
      psychic: 1,
      bug: 2,
      rock: 1,
      ghost: 1,
      dragon: 1,
      dark: 1,
      steel: 0.5,
      fairy: 1,
    },
    weakness: ['fighting', 'ground', 'steel', 'water', 'grass'],
  },
  {
    name: 'ghost',
    color: {
      base: 'hsl(266.3,26.9%,46.7%)',
      lighten: 'hsl(266.3,26.9%,66.7%)',
      darken: 'hsl(266.3,26.9%,26.7%)',
    },
    type: 'ghost',
    damage: {
      normal: 0,
      fire: 1,
      water: 1,
      electric: 1,
      grass: 1,
      ice: 1,
      fighting: 1,
      poison: 1,
      ground: 1,
      flying: 1,
      psychic: 2,
      bug: 1,
      rock: 1,
      ghost: 2,
      dragon: 1,
      dark: 0.5,
      steel: 1,
      fairy: 1,
    },
    weakness: ['ghost', 'dark'],
  },
  {
    name: 'dragon',
    color: {
      base: 'hsl(257.5,97.1%,59.8%)',
      lighten: 'hsl(257.5,97.1%,79.8%)',
      darken: 'hsl(257.5,97.1%,39.8%)',
    },
    type: 'dragon',
    damage: {
      normal: 1,
      fire: 0.5,
      water: 0.5,
      electric: 0.5,
      grass: 0.5,
      ice: 2,
      fighting: 1,
      poison: 1,
      ground: 1,
      flying: 1,
      psychic: 1,
      bug: 1,
      rock: 1,
      ghost: 1,
      dragon: 2,
      dark: 1,
      steel: 0.5,
      fairy: 0,
    },
    weakness: ['ice', 'dragon', 'fairy'],
  },
  {
    name: 'dark',
    color: {
      base: 'hsl(24.3,23.1%,35.7%)',
      lighten: 'hsl(24.3,23.1%,55.7%)',
      darken: 'hsl(24.3,23.1%,15.7%)',
    },
    type: 'dark',
    damage: {
      normal: 1,
      fire: 1,
      water: 1,
      electric: 1,
      grass: 1,
      ice: 1,
      fighting: 0.5,
      poison: 1,
      ground: 1,
      flying: 1,
      psychic: 2,
      bug: 1,
      rock: 1,
      ghost: 2,
      dragon: 1,
      dark: 0.5,
      steel: 1,
      fairy: 0.5,
    },
    weakness: ['fighting', 'bug', 'fairy'],
  },
  {
    name: 'steel',
    color: {
      base: 'hsl(240,19%,76.3%)',
      lighten: 'hsl(240,19%,96.3%)',
      darken: 'hsl(240,19%,56.3%)',
    },
    type: 'steel',
    damage: {
      normal: 1,
      fire: 0.5,
      water: 0.5,
      electric: 0.5,
      grass: 1,
      ice: 2,
      fighting: 2,
      poison: 1,
      ground: 1,
      flying: 1,
      psychic: 1,
      bug: 1,
      rock: 2,
      ghost: 1,
      dragon: 1,
      dark: 1,
      steel: 0.5,
      fairy: 2,
    },
    weakness: ['fire', 'fighting', 'ground'],
  },
  {
    name: 'fairy',
    color: {
      base: 'hsl(330.4,49.7%,68%)',
      lighten: 'hsl(330.4,49.7%,88%)',
      darken: 'hsl(330.4,49.7%,48%)',
    },
    type: 'fairy',
    damage: {
      normal: 1,
      fire: 0.5,
      water: 1,
      electric: 1,
      grass: 1,
      ice: 1,
      fighting: 2,
      poison: 0.5,
      ground: 1,
      flying: 1,
      psychic: 1,
      bug: 1,
      rock: 1,
      ghost: 1,
      dragon: 2,
      dark: 2,
      steel: 0.5,
      fairy: 1,
    },
    weakness: ['poison', 'steel'],
  },
]; */

export const TYPES_DAMAGES: TypesDamages = {
  [POKEMON_TYPE.WATER]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 2,
    [POKEMON_TYPE.WATER]: 0.5,
    [POKEMON_TYPE.GRASS]: 0.5,
    [POKEMON_TYPE.ELECTRIC]: 0.5,
    [POKEMON_TYPE.ICE]: 1,
    [POKEMON_TYPE.FIGHTING]: 1,
    [POKEMON_TYPE.POISON]: 1,
    [POKEMON_TYPE.GROUND]: 2,
    [POKEMON_TYPE.FLYING]: 1,
    [POKEMON_TYPE.PSYCHIC]: 1,
    [POKEMON_TYPE.BUG]: 1,
    [POKEMON_TYPE.ROCK]: 2,
    [POKEMON_TYPE.GHOST]: 1,
    [POKEMON_TYPE.DRAGON]: 0.5,
    [POKEMON_TYPE.DARK]: 1,
    [POKEMON_TYPE.STEEL]: 1,
    [POKEMON_TYPE.FAIRY]: 1,
  },
  [POKEMON_TYPE.FIRE]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 0.5,
    [POKEMON_TYPE.WATER]: 0.5,
    [POKEMON_TYPE.ELECTRIC]: 1,
    [POKEMON_TYPE.GRASS]: 2,
    [POKEMON_TYPE.ICE]: 2,
    [POKEMON_TYPE.FIGHTING]: 1,
    [POKEMON_TYPE.POISON]: 1,
    [POKEMON_TYPE.GROUND]: 1,
    [POKEMON_TYPE.FLYING]: 1,
    [POKEMON_TYPE.PSYCHIC]: 1,
    [POKEMON_TYPE.BUG]: 2,
    [POKEMON_TYPE.ROCK]: 0.5,
    [POKEMON_TYPE.GHOST]: 1,
    [POKEMON_TYPE.DRAGON]: 0.5,
    [POKEMON_TYPE.DARK]: 1,
    [POKEMON_TYPE.STEEL]: 2,
    [POKEMON_TYPE.FAIRY]: 1,
  },
  [POKEMON_TYPE.NORMAL]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 1,
    [POKEMON_TYPE.WATER]: 1,
    [POKEMON_TYPE.ELECTRIC]: 1,
    [POKEMON_TYPE.GRASS]: 1,
    [POKEMON_TYPE.ICE]: 1,
    [POKEMON_TYPE.FIGHTING]: 1,
    [POKEMON_TYPE.POISON]: 1,
    [POKEMON_TYPE.GROUND]: 1,
    [POKEMON_TYPE.FLYING]: 1,
    [POKEMON_TYPE.PSYCHIC]: 1,
    [POKEMON_TYPE.BUG]: 1,
    [POKEMON_TYPE.ROCK]: 0.5,
    [POKEMON_TYPE.GHOST]: 0,
    [POKEMON_TYPE.DRAGON]: 1,
    [POKEMON_TYPE.DARK]: 1,
    [POKEMON_TYPE.STEEL]: 0.5,
    [POKEMON_TYPE.FAIRY]: 1,
  },
  [POKEMON_TYPE.ELECTRIC]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 1,
    [POKEMON_TYPE.WATER]: 2,
    [POKEMON_TYPE.ELECTRIC]: 0.5,
    [POKEMON_TYPE.GRASS]: 0.5,
    [POKEMON_TYPE.ICE]: 1,
    [POKEMON_TYPE.FIGHTING]: 1,
    [POKEMON_TYPE.POISON]: 1,
    [POKEMON_TYPE.GROUND]: 0,
    [POKEMON_TYPE.FLYING]: 2,
    [POKEMON_TYPE.PSYCHIC]: 1,
    [POKEMON_TYPE.BUG]: 1,
    [POKEMON_TYPE.ROCK]: 1,
    [POKEMON_TYPE.GHOST]: 1,
    [POKEMON_TYPE.DRAGON]: 0.5,
    [POKEMON_TYPE.DARK]: 1,
    [POKEMON_TYPE.STEEL]: 1,
    [POKEMON_TYPE.FAIRY]: 1,
  },
  [POKEMON_TYPE.GRASS]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 0.5,
    [POKEMON_TYPE.WATER]: 2,
    [POKEMON_TYPE.ELECTRIC]: 1,
    [POKEMON_TYPE.GRASS]: 0.5,
    [POKEMON_TYPE.ICE]: 1,
    [POKEMON_TYPE.FIGHTING]: 1,
    [POKEMON_TYPE.POISON]: 0.5,
    [POKEMON_TYPE.GROUND]: 2,
    [POKEMON_TYPE.FLYING]: 0.5,
    [POKEMON_TYPE.PSYCHIC]: 1,
    [POKEMON_TYPE.BUG]: 0.5,
    [POKEMON_TYPE.ROCK]: 2,
    [POKEMON_TYPE.GHOST]: 1,
    [POKEMON_TYPE.DRAGON]: 0.5,
    [POKEMON_TYPE.DARK]: 1,
    [POKEMON_TYPE.STEEL]: 0.5,
    [POKEMON_TYPE.FAIRY]: 1,
  },
  [POKEMON_TYPE.ICE]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 0.5,
    [POKEMON_TYPE.WATER]: 0.5,
    [POKEMON_TYPE.ELECTRIC]: 1,
    [POKEMON_TYPE.GRASS]: 2,
    [POKEMON_TYPE.ICE]: 0.5,
    [POKEMON_TYPE.FIGHTING]: 1,
    [POKEMON_TYPE.POISON]: 1,
    [POKEMON_TYPE.GROUND]: 2,
    [POKEMON_TYPE.FLYING]: 2,
    [POKEMON_TYPE.PSYCHIC]: 1,
    [POKEMON_TYPE.BUG]: 1,
    [POKEMON_TYPE.ROCK]: 1,
    [POKEMON_TYPE.GHOST]: 1,
    [POKEMON_TYPE.DRAGON]: 2,
    [POKEMON_TYPE.DARK]: 1,
    [POKEMON_TYPE.STEEL]: 0.5,
    [POKEMON_TYPE.FAIRY]: 1,
  },
  [POKEMON_TYPE.FIGHTING]: {
    [POKEMON_TYPE.NORMAL]: 2,
    [POKEMON_TYPE.FIRE]: 1,
    [POKEMON_TYPE.WATER]: 1,
    [POKEMON_TYPE.ELECTRIC]: 1,
    [POKEMON_TYPE.GRASS]: 1,
    [POKEMON_TYPE.ICE]: 2,
    [POKEMON_TYPE.FIGHTING]: 1,
    [POKEMON_TYPE.POISON]: 0.5,
    [POKEMON_TYPE.GROUND]: 1,
    [POKEMON_TYPE.FLYING]: 0.5,
    [POKEMON_TYPE.PSYCHIC]: 0.5,
    [POKEMON_TYPE.BUG]: 0.5,
    [POKEMON_TYPE.ROCK]: 2,
    [POKEMON_TYPE.GHOST]: 0,
    [POKEMON_TYPE.DRAGON]: 1,
    [POKEMON_TYPE.DARK]: 2,
    [POKEMON_TYPE.STEEL]: 2,
    [POKEMON_TYPE.FAIRY]: 0.5,
  },
  [POKEMON_TYPE.POISON]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 1,
    [POKEMON_TYPE.WATER]: 1,
    [POKEMON_TYPE.ELECTRIC]: 1,
    [POKEMON_TYPE.GRASS]: 2,
    [POKEMON_TYPE.ICE]: 1,
    [POKEMON_TYPE.FIGHTING]: 1,
    [POKEMON_TYPE.POISON]: 0.5,
    [POKEMON_TYPE.GROUND]: 0.5,
    [POKEMON_TYPE.FLYING]: 1,
    [POKEMON_TYPE.PSYCHIC]: 1,
    [POKEMON_TYPE.BUG]: 1,
    [POKEMON_TYPE.ROCK]: 0.5,
    [POKEMON_TYPE.GHOST]: 0.5,
    [POKEMON_TYPE.DRAGON]: 1,
    [POKEMON_TYPE.DARK]: 1,
    [POKEMON_TYPE.STEEL]: 0,
    [POKEMON_TYPE.FAIRY]: 2,
  },
  [POKEMON_TYPE.GROUND]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 2,
    [POKEMON_TYPE.WATER]: 1,
    [POKEMON_TYPE.ELECTRIC]: 2,
    [POKEMON_TYPE.GRASS]: 0.5,
    [POKEMON_TYPE.ICE]: 1,
    [POKEMON_TYPE.FIGHTING]: 1,
    [POKEMON_TYPE.POISON]: 2,
    [POKEMON_TYPE.GROUND]: 1,
    [POKEMON_TYPE.FLYING]: 0,
    [POKEMON_TYPE.PSYCHIC]: 1,
    [POKEMON_TYPE.BUG]: 0.5,
    [POKEMON_TYPE.ROCK]: 2,
    [POKEMON_TYPE.GHOST]: 1,
    [POKEMON_TYPE.DRAGON]: 1,
    [POKEMON_TYPE.DARK]: 1,
    [POKEMON_TYPE.STEEL]: 2,
    [POKEMON_TYPE.FAIRY]: 1,
  },
  [POKEMON_TYPE.FLYING]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 1,
    [POKEMON_TYPE.WATER]: 1,
    [POKEMON_TYPE.ELECTRIC]: 0.5,
    [POKEMON_TYPE.GRASS]: 2,
    [POKEMON_TYPE.ICE]: 1,
    [POKEMON_TYPE.FIGHTING]: 2,
    [POKEMON_TYPE.POISON]: 1,
    [POKEMON_TYPE.GROUND]: 1,
    [POKEMON_TYPE.FLYING]: 1,
    [POKEMON_TYPE.PSYCHIC]: 1,
    [POKEMON_TYPE.BUG]: 2,
    [POKEMON_TYPE.ROCK]: 0.5,
    [POKEMON_TYPE.GHOST]: 1,
    [POKEMON_TYPE.DRAGON]: 1,
    [POKEMON_TYPE.DARK]: 1,
    [POKEMON_TYPE.STEEL]: 0.5,
    [POKEMON_TYPE.FAIRY]: 1,
  },
  [POKEMON_TYPE.PSYCHIC]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 1,
    [POKEMON_TYPE.WATER]: 1,
    [POKEMON_TYPE.ELECTRIC]: 1,
    [POKEMON_TYPE.GRASS]: 1,
    [POKEMON_TYPE.ICE]: 1,
    [POKEMON_TYPE.FIGHTING]: 2,
    [POKEMON_TYPE.POISON]: 2,
    [POKEMON_TYPE.GROUND]: 1,
    [POKEMON_TYPE.FLYING]: 1,
    [POKEMON_TYPE.PSYCHIC]: 0.5,
    [POKEMON_TYPE.BUG]: 1,
    [POKEMON_TYPE.ROCK]: 1,
    [POKEMON_TYPE.GHOST]: 1,
    [POKEMON_TYPE.DRAGON]: 1,
    [POKEMON_TYPE.DARK]: 0,
    [POKEMON_TYPE.STEEL]: 0.5,
    [POKEMON_TYPE.FAIRY]: 1,
  },
  [POKEMON_TYPE.BUG]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 0.5,
    [POKEMON_TYPE.WATER]: 1,
    [POKEMON_TYPE.ELECTRIC]: 1,
    [POKEMON_TYPE.GRASS]: 2,
    [POKEMON_TYPE.ICE]: 1,
    [POKEMON_TYPE.FIGHTING]: 0.5,
    [POKEMON_TYPE.POISON]: 0.5,
    [POKEMON_TYPE.GROUND]: 1,
    [POKEMON_TYPE.FLYING]: 0.5,
    [POKEMON_TYPE.PSYCHIC]: 2,
    [POKEMON_TYPE.BUG]: 1,
    [POKEMON_TYPE.ROCK]: 1,
    [POKEMON_TYPE.GHOST]: 0.5,
    [POKEMON_TYPE.DRAGON]: 1,
    [POKEMON_TYPE.DARK]: 2,
    [POKEMON_TYPE.STEEL]: 0.5,
    [POKEMON_TYPE.FAIRY]: 0.5,
  },
  [POKEMON_TYPE.ROCK]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 2,
    [POKEMON_TYPE.WATER]: 1,
    [POKEMON_TYPE.ELECTRIC]: 1,
    [POKEMON_TYPE.GRASS]: 1,
    [POKEMON_TYPE.ICE]: 2,
    [POKEMON_TYPE.FIGHTING]: 0.5,
    [POKEMON_TYPE.POISON]: 1,
    [POKEMON_TYPE.GROUND]: 0.5,
    [POKEMON_TYPE.FLYING]: 2,
    [POKEMON_TYPE.PSYCHIC]: 1,
    [POKEMON_TYPE.BUG]: 2,
    [POKEMON_TYPE.ROCK]: 1,
    [POKEMON_TYPE.GHOST]: 1,
    [POKEMON_TYPE.DRAGON]: 1,
    [POKEMON_TYPE.DARK]: 1,
    [POKEMON_TYPE.STEEL]: 0.5,
    [POKEMON_TYPE.FAIRY]: 1,
  },
  [POKEMON_TYPE.GHOST]: {
    [POKEMON_TYPE.NORMAL]: 0,
    [POKEMON_TYPE.FIRE]: 1,
    [POKEMON_TYPE.WATER]: 1,
    [POKEMON_TYPE.ELECTRIC]: 1,
    [POKEMON_TYPE.GRASS]: 1,
    [POKEMON_TYPE.ICE]: 1,
    [POKEMON_TYPE.FIGHTING]: 1,
    [POKEMON_TYPE.POISON]: 1,
    [POKEMON_TYPE.GROUND]: 1,
    [POKEMON_TYPE.FLYING]: 1,
    [POKEMON_TYPE.PSYCHIC]: 2,
    [POKEMON_TYPE.BUG]: 1,
    [POKEMON_TYPE.ROCK]: 1,
    [POKEMON_TYPE.GHOST]: 2,
    [POKEMON_TYPE.DRAGON]: 1,
    [POKEMON_TYPE.DARK]: 0.5,
    [POKEMON_TYPE.STEEL]: 1,
    [POKEMON_TYPE.FAIRY]: 1,
  },
  [POKEMON_TYPE.DRAGON]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 0.5,
    [POKEMON_TYPE.WATER]: 0.5,
    [POKEMON_TYPE.ELECTRIC]: 0.5,
    [POKEMON_TYPE.GRASS]: 0.5,
    [POKEMON_TYPE.ICE]: 2,
    [POKEMON_TYPE.FIGHTING]: 1,
    [POKEMON_TYPE.POISON]: 1,
    [POKEMON_TYPE.GROUND]: 1,
    [POKEMON_TYPE.FLYING]: 1,
    [POKEMON_TYPE.PSYCHIC]: 1,
    [POKEMON_TYPE.BUG]: 1,
    [POKEMON_TYPE.ROCK]: 1,
    [POKEMON_TYPE.GHOST]: 1,
    [POKEMON_TYPE.DRAGON]: 2,
    [POKEMON_TYPE.DARK]: 1,
    [POKEMON_TYPE.STEEL]: 0.5,
    [POKEMON_TYPE.FAIRY]: 0,
  },
  [POKEMON_TYPE.DARK]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 1,
    [POKEMON_TYPE.WATER]: 1,
    [POKEMON_TYPE.ELECTRIC]: 1,
    [POKEMON_TYPE.GRASS]: 1,
    [POKEMON_TYPE.ICE]: 1,
    [POKEMON_TYPE.FIGHTING]: 0.5,
    [POKEMON_TYPE.POISON]: 1,
    [POKEMON_TYPE.GROUND]: 1,
    [POKEMON_TYPE.FLYING]: 1,
    [POKEMON_TYPE.PSYCHIC]: 2,
    [POKEMON_TYPE.BUG]: 1,
    [POKEMON_TYPE.ROCK]: 1,
    [POKEMON_TYPE.GHOST]: 2,
    [POKEMON_TYPE.DRAGON]: 1,
    [POKEMON_TYPE.DARK]: 0.5,
    [POKEMON_TYPE.STEEL]: 1,
    [POKEMON_TYPE.FAIRY]: 0.5,
  },
  [POKEMON_TYPE.STEEL]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 0.5,
    [POKEMON_TYPE.WATER]: 0.5,
    [POKEMON_TYPE.ELECTRIC]: 0.5,
    [POKEMON_TYPE.GRASS]: 1,
    [POKEMON_TYPE.ICE]: 2,
    [POKEMON_TYPE.FIGHTING]: 2,
    [POKEMON_TYPE.POISON]: 1,
    [POKEMON_TYPE.GROUND]: 1,
    [POKEMON_TYPE.FLYING]: 1,
    [POKEMON_TYPE.PSYCHIC]: 1,
    [POKEMON_TYPE.BUG]: 1,
    [POKEMON_TYPE.ROCK]: 2,
    [POKEMON_TYPE.GHOST]: 1,
    [POKEMON_TYPE.DRAGON]: 1,
    [POKEMON_TYPE.DARK]: 1,
    [POKEMON_TYPE.STEEL]: 0.5,
    [POKEMON_TYPE.FAIRY]: 2,
  },
  [POKEMON_TYPE.FAIRY]: {
    [POKEMON_TYPE.NORMAL]: 1,
    [POKEMON_TYPE.FIRE]: 0.5,
    [POKEMON_TYPE.WATER]: 1,
    [POKEMON_TYPE.ELECTRIC]: 1,
    [POKEMON_TYPE.GRASS]: 1,
    [POKEMON_TYPE.ICE]: 1,
    [POKEMON_TYPE.FIGHTING]: 2,
    [POKEMON_TYPE.POISON]: 0.5,
    [POKEMON_TYPE.GROUND]: 1,
    [POKEMON_TYPE.FLYING]: 1,
    [POKEMON_TYPE.PSYCHIC]: 1,
    [POKEMON_TYPE.BUG]: 1,
    [POKEMON_TYPE.ROCK]: 1,
    [POKEMON_TYPE.GHOST]: 1,
    [POKEMON_TYPE.DRAGON]: 2,
    [POKEMON_TYPE.DARK]: 2,
    [POKEMON_TYPE.STEEL]: 0.5,
    [POKEMON_TYPE.FAIRY]: 1,
  },
};
